services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    networks:
      - microservices-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - microservices-network


  eureka-server:
    container_name: eureka-server
    image: eureka-server
    ports:
      - "8761:8761"
    expose:
        - "8761"
    restart: always
    networks:
      - microservices-network

  config-server:
    container_name: config-server
    image: config-server:latest
    ports:
      - "8888:8888"
    expose:
      - "8888"
    restart: always
    depends_on:
        - eureka-server
    networks:
      - microservices-network
  RTDS:
    container_name: rtds-server
    image: rtds-server
    ports:
      - "8081:8081"
    expose:
      - "8081"
    restart: always
    depends_on:
      - eureka-server
      - config-server
      - kafka
    networks:
      - microservices-network
networks:
  microservices-network:
    driver: bridge