services:
  eureka-server:
    container_name: eureka-server
    image: eureka-server
    ports:
      - "8761:8761"
    expose:
        - "8761"
    restart: always
    networks:
      - microservices-network

  config-server:
    container_name: config-server
    image: config-server:latest
    ports:
      - "8888:8888"
    expose:
      - "8888"
    restart: always
    depends_on:
        - eureka-server
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge